Traceback (most recent call last):
  File "/home/chris/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/chris/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/chris/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/chris/miniconda3/envs/jupyterbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/chris/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/chris/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/chris/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
######################################################
# Converting wide-format datasets to long-format ones#
######################################################

def convert_wide_to_long(file_path, skiprows=4, id_vars=None, var_name="Year", value_name="Value"):
    # Load the CSV file
    df = pd.read_csv(file_path, skiprows=skiprows)
    
    # Automatically determine id_vars if not provided
    if id_vars is None:
        id_vars = df.columns[:4]  # First 4 columns are IDs
    
    # Melt the DataFrame
    df_long = pd.melt(df, id_vars=id_vars, var_name=var_name, value_name=value_name)
    
    # Optionally drop rows with missing values in the value column
    # df_long.dropna(subset=[value_name], inplace=True)

    return df_long

# Convert economy csv to long format
file_path1 = "og_csv_files/API_3_DS2_en_csv_v2_390106.csv"
world_bank_long_format = convert_wide_to_long(file_path1)

# convert GINI csv to long format
filepath2 = "og_csv_files/API_SI.POV.GINI_DS2_en_csv_v2_2566.csv"
gini_long_format = convert_wide_to_long(filepath2)

#save as new files to [path]
#output_csv_path1 = "world bank long format2.csv"
#output_csv_path2 = "gini long2.csv"
#df_long1.to_csv(output_csv_path1, index=False)
#df_long2.to_csv(output_csv_path2, index=False)

###############################################################################
# EU dataset pivot so that the different types of crime get their own columns #
###############################################################################

# Load the dataset
eu_df = pd.read_csv("og_csv_files/estat_crim_off_cat_filtered_en.csv")

# Pivot the data so that all types of crime have their own column
df_pivot = eu_df.pivot_table(
    index=["Geopolitical entity (reporting)", "TIME_PERIOD"],
    columns="International classification of crime for statistical purposes (ICCS)",
    values="OBS_VALUE"
).reset_index()

# save to new file
df_pivot.to_csv("europe_crime_definitive.csv")


------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpandas[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mpd[39;00m
[1;32m      2[0m [38;5;66;03m######################################################[39;00m
[1;32m      3[0m [38;5;66;03m# Converting wide-format datasets to long-format ones#[39;00m
[1;32m      4[0m [38;5;66;03m######################################################[39;00m
[1;32m      6[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mconvert_wide_to_long[39m(file_path, skiprows[38;5;241m=[39m[38;5;241m4[39m, id_vars[38;5;241m=[39m[38;5;28;01mNone[39;00m, var_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mYear[39m[38;5;124m"[39m, value_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mValue[39m[38;5;124m"[39m):
[1;32m      7[0m     [38;5;66;03m# Load the CSV file[39;00m

[0;31mModuleNotFoundError[0m: No module named 'pandas'

